on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      directory_path:
      sphinx_commands: clean html linkcheck # commands to run. Update accordingly
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Sphinx install
        run: pip install --upgrade sphinx
      - name: Set directory
        run:  |
          VAR=${{ env.directory_path }}
          echo "docs_dir="${VAR:-./docs} >> $GITHUB_ENV
      - name: Build doc
        run: |
          cd $docs_dir
          make ${{ env.sphinx_commands }}
